version: "3.1"
services:
  app:
    build: src/flask-app/.    
    ports: 
      - "5000:5000"
    depends_on:
      - db  
    links:
      - db
    
  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: 0.0.0.0
      
    # First item in list is to persist data in containers. 
    # And second in list is to initialise db inside container. 
    volumes:
      - ./src/db/db_data:/var/lib/mysql      
      - ./src/db/dbinit:/docker-entrypoint-initdb.d/:ro   
